name: opened
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - statsmodels
  - ipywidgets
  - pyaudio=0.2.11
  - keyboard
  - jupyterlab
  - pip
  - pip:
    - pyserial
    - jupyter-book

